<<<<<<< HEAD
version: '3.4'

services:
  ecommerce:
    image: ecommerce
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
=======
version: '3.7'

services:
 app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - 3000:3000
    volumes:
      - ./:/home/app/
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
>>>>>>> main
