services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - 3000:3000
    volumes:
      - ./:/home/app/
    networks:
      - app-network
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    image: mysql:8.0.21
    container_name: mysql-ecommerce
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ecommerce_db_default:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ecommerce_db_default: {}
