version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node-app
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./:/home/app/
    networks:
      - app-network
<<<<<<< HEAD
=======
    depends_on:
      - mysqldb
    links:
      - mysqldb
    
>>>>>>> 62b21158499c6e118495eb26a31555d407b1eb48
    
  mysqldb:
    image: mysql:8.0.21
    container_name: mysql-Damartec
    env_file:
      - ./.env
    ports:
     - 3306:3306
    volumes:
     - damartec-default:/var/lib/mysql
    networks: 
     - app-network
<<<<<<< HEAD

volumes:
  damartec-default: {}

       
=======
>>>>>>> 62b21158499c6e118495eb26a31555d407b1eb48

volumes:
  damartec-default: {}
  

networks:
  app-network:
    driver: bridge