version: '3.4'

services:
  ecommerce:
    image: ecommerce
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
<<<<<<< HEAD
      - 3000:3000
=======
      - 3001:3001
>>>>>>> Margarida_manuel
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
